#!/bin/bash
set -e
set -u

export PATH=$PATH:/bin:/opt/sge6.2/bin/lx24-amd64
export SGE_CELL=default
export SGE_EXECD_PORT=537
export SGE_QMASTER_PORT=536
export SGE_ROOT=/opt/sge6.2
export SGE_CLUSTER_NAME=Ranger

job_map=/var/run/ibtop-job-map
tmp=$(mktemp ${job_map}.XXXXXXXX)

# Translates qconf -j's busted output to sane '<hostname> <jobid>'
# form.  Not thoroughly tested, but works for me.

qhost -j | awk '{
  if ($0 ~ /^[[:alpha:]]/) {
    current_host = $1;
    need_job = 1;
  } else if (need_job && $1 ~ /^[0-9]+$/) {
    print current_host, $1, $4;
    need_job = 0;
  }
}' > $tmp

mv $tmp $job_map
